inventory/urls.py
from django.conf.urls import include,patterns, url
from inventory import views

urlpatterns = patterns('inventory.views',
    # Examples:
    url(r'^$', 'index', name='index'),
    url(r'^$', 'index_template', name='index_template'),
    url(r'^$', 'home', name='home'),
    )

woolston_bb/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from woolston_bb import settings
from django.conf.urls.static import static

#Models
from inventory.models import *
#Forms
from inventory.forms import *
#Views
from inventory.views import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

#List Views
    url(r'^home', HomePageView.as_view(page_name = 'Welcome'), name='home'),
    url(r'^musicpacks', ModelListView.as_view(model = MusicPack, page_name = 'Music Packs',edit_link = 'updatemusicpack/'), name='musicpack-list'),
    url(r'^instruments', ModelListView.as_view(model = Instrument,page_name = 'Instruments',edit_link = 'updateinstrument/'), name='instrument-list'),
    url(r'^members', ModelListView.as_view(model = Member,page_name = 'Members',edit_link = 'updatemember/'), name='member-list'),
    url(r'^roles', ModelListView.as_view(model = MemberRole, page_name = 'Member Roles',edit_link = 'updatememberrole/'), name='memberrole-list'),
    url(r'^uniforms', ModelListView.as_view(model = Uniform, page_name = 'Uniforms',edit_link = 'updateuniform'), name='uniform-list'),
    url(r'^transactions', ModelListView.as_view(model = Transaction, page_name = 'Transactions',edit_link = 'updatetransaction'), name='transaction-list'),

#Create Views
    url(r'^newinstrument', ModelCreateView.as_view(model = Instrument, model_url = 'instrument-new',model_list = 'instrument-list',  page_name = 'Instrument',form_class = InstrumentForm), name='instrument-new'),
    url(r'^newmemberrole', ModelCreateView.as_view(model = MemberRole, model_url = 'memberrole-new',model_list = 'memberrole-list',  page_name = 'Member Role',form_class = MemberRoleForm), name='memberrole-new'),
    
    url(r'^addrole', 'inventory.views.add_role', name = 'role-add'),
    url(r'^newmember', 'inventory.views.add_member', name = 'member-new'),

    url(r'^newuniform', ModelCreateView.as_view(model = Uniform, model_url = 'uniform-new',model_list = 'uniform-list',  page_name = 'Uniform',form_class = UniformForm), name='uniform-new'),
    url(r'^newtransaction', 'inventory.views.add_transaction', name = 'transaction-new'),
    url(r'^newmusicpack', 'inventory.views.add_musicpack', name = 'musicpack-new'), 
    url(r'^filltransactionfields', 'inventory.views.fill_transaction_fields'),

#Update Views
    url(r'^updatememberrole/(?P<pk>[\w-]+)$', ModelUpdateView.as_view(model = MemberRole, model_url = 'memberrole-new',model_list = 'memberrole-list',page_name = 'Member Role'), name='memberrole-update'),
    url(r'^updatemusicpack/(?P<pk>[\w-]+)$', ModelUpdateView.as_view(model = MusicPack, model_url = 'musicpack-new',model_list = 'musicpack-list',page_name = 'Music Pack'), name='musicpack-update'),
    url(r'^updatemember/(?P<pk>[\w-]+)$', ModelUpdateView.as_view(model = Member, model_url = 'member-new',model_list = 'member-list',page_name = 'Member'), name='member-update'),
    url(r'^updateinstrument/(?P<pk>[\w-]+)$', ModelUpdateView.as_view(model = Instrument, model_url = 'instrument-new',model_list = 'instrument-list', page_name = 'Instrument'), name='instrument-update'),
    url(r'^updateuniform/(?P<pk>[\w-]+)$', ModelUpdateView.as_view(model = Uniform, model_url = 'uniform-new',model_list = 'uniform-list', page_name = 'Uniform'), name='uniform-update'),
    url(r'^updatetransaction/(?P<pk>[\w-]+)$', ModelUpdateView.as_view(model = Transaction, model_url = 'transacction-new',model_list = 'transaction-list', page_name = 'Transaction'), name='transaction-update'),


    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)
urlpatterns += staticfiles_urlpatterns()

inventory/models.py
from django.db import models, transaction, IntegrityError
from django.utils.translation import ugettext as _
from django.utils import timezone
import datetime

#add music model

class get_fields(object):
    def get_fields(self):
        return[(field.name, field.value_to_string(self)) for field in self.__class__._meta.fields]

class Music(models.Model,get_fields):
    name = models.CharField(max_length = 20)

    def __unicode__(self): 
        return self.name

class MusicPack(models.Model,get_fields):
    title = models.CharField(max_length = 20)
    composer = models.CharField(max_length = 20) 
    arranger = models.CharField(max_length = 20)
    music = models.ManyToManyField(Music)

    def __unicode__(self): 
        return self.title +' - '+ self.composer +' - '+ self.arranger

    #Combined Primary key
    class Meta:
        unique_together = ('title', 'composer','arranger')


class Instrument(models.Model,get_fields):
    TYPES_CHOICES = (
        ('ACADEMY', 'Academy'),
        ('SENIOR', 'Senior'),
        ('PERCUSSION', 'Percussion')
    )
    type = models.CharField(_('Type'), max_length = 20, choices = TYPES_CHOICES)
    name = models.CharField(max_length = 20)
    serial = models.CharField(max_length = 30, primary_key = True)

    def __unicode__(self): 
        return self.serial + " - " + self.name

class MemberRole(models.Model,get_fields):
    name = models.CharField(max_length = 20)
        
    def __unicode__(self): 
        return self.name

class Member(models.Model,get_fields):
    first_name = models.CharField(max_length = 20)
    last_name = models.CharField(max_length = 20)
    street_line1 = models.CharField(_('Address 1'), max_length = 100, blank = True)
    street_line2 = models.CharField(_('Address 2'), max_length = 100, blank = True)
    zipcode = models.CharField(_('ZIP code'), max_length = 5, blank = True)
    city = models.CharField(_('City'), max_length = 100, blank = True)
    number = models.CharField(max_length = 20)
    email = models.EmailField(max_length = 254)
    role = models.ManyToManyField(MemberRole)

    def __unicode__(self):
        return self.last_name + " - " + unicode(self.pk)
        
class Uniform(models.Model,get_fields):
    SIZE_CHOICES = (
        ('SMALL', 'Small'),
        ('MEDIUM', 'Medium'),
        ('LARGE', 'Large'),
        ('XLARGE', 'X Large')
    )
    size = models.CharField(_('Size'), max_length= 20, choices = SIZE_CHOICES)
    name = models.CharField(max_length = 20)
    serial = models.CharField(max_length = 30, primary_key = True)

    def __unicode__(self):
        return self.serial +" - "+ self.name

class Transaction(models.Model,get_fields):
    member = models.ForeignKey(Member)
    date = models.DateTimeField(default= timezone.now,blank=True)
    instrument = models.ManyToManyField(Instrument)
    uniform = models.ManyToManyField(Uniform)

    def __unicode__(self):
        return unicode(self.member) +" - "+ unicode(self.date)

class OtherState(models.Model):
    state = models.CharField(max_length = 20)
    def __unicode__(self): 
        return self.state

class MusicPackState(models.Model):
    TYPES_CHOICES = ( 
        ('ISSUED', 'Issued'),
        ('LIBRARY', 'Library'),
        ('LOAN', 'Loan'),
        ('ENTERTAINMENTFOLDER', 'Entertainment Folder'),
        ('OTHER', 'Other')
    )
    type = models.CharField(_('Type'), max_length = 20, choices = TYPES_CHOICES)
    member = models.ForeignKey(Member)
    music_pack = models.ForeignKey(MusicPack,null = True, blank = True)
    other_states = models.ForeignKey(OtherState, null = True, blank = True)

    def if_loan(self):
        if type in ['LIBRARY','ENTERTAINMENT','ISSUED']:
           self.member = None

inventory/forms.py
from django import forms
from inventory.models import *
from django.utils import timezone

class MemberRoleForm(forms.ModelForm):
    class Meta:
         model = MemberRole

class MemberForm(forms.ModelForm):
    role = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=MemberRole.objects.all().order_by('name'))
    class Meta:
        model = Member


class MusicPackForm(forms.ModelForm):
    music = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=Music.objects.all().order_by('name'))
    class Meta:
         model = MusicPack

class InstrumentForm(forms.ModelForm):
    class Meta:
         model = Instrument


class UniformForm(forms.ModelForm):
    class Meta:
         model = Uniform

class TransactionForm(forms.ModelForm):
    instrument = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=Instrument.objects.all().order_by('name'))
    uniform = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=Uniform.objects.all().order_by('name'))
    class Meta:
        model = Transaction

templates/create_model.html
{% extends 'template.html' %}
{%block title %} Create {{page_name}} {% endblock%}
{%block header %} Create {{page_name}} {% endblock%}

{% block body_block %}
<div class = "subtemplate">
        
    <div id="fade" class="black_overlay"></div>
	<form id ="membercreate" action="" method="POST">
	  {% csrf_token %}
	  
	  {% if model_url == 'member-add' %}

		    {% for field in member_form %}

				        {% if field.label == 'First name' %}
				        
				        <div class="formname">
				       	<h4>Name</h4>
				            {{ field.errors }}
				            {{ field.label_tag }} {{ field }}
				        </div>
				    	{% endif %}
				    	{% if field.label == 'Last name' %}
				        <div class="formname">
				            {{ field.errors }}
				            {{ field.label_tag }} {{ field }}
				        </div>
				    	{% endif %}

				    	{% if field.label == 'Address 1' %}
				        <div class="formaddress">
				       	<h4>Address</h4>
				            {{ field.errors }}
				            {{ field.label_tag }} {{ field }}
				        </div>
				    	{% endif %}
				    	{% if field.label == 'Address 2' %}
				        <div class="formaddress">
				            {{ field.errors }}
				            {{ field.label_tag }} {{ field }}
				        </div>
				    	{% endif %}
				    	{% if field.label == 'ZIP code' %}
				        <div class="formaddress">
				            {{ field.errors }}
				            {{ field.label_tag }} {{ field }}
				        </div>
				        {% endif %}
				    	{%if field.label == 'City' %}
				        <div class="formaddress">
				            {{ field.errors }}
				            {{ field.label_tag }} {{ field }}
				        </div>
				    	{% endif %}



				    	{% if field.label == 'Role' %}
				    	<h4 id = "role"> Roles</h4>
				    	<div id = "refresh">
							<div class="formrole">
				        	    {{ field.errors }}
				          	  	{{ field }}
				          	  	
					        </div>
				        </div>
				        <input id="showcreaterolebut" type="button" onclick=lightdiv() value="Create New Role"/>
				        {% endif %}



				    	{%if field.label == 'Number' %}
				        <div class="formcontact">
				        <h4>Contact</h4>
				            {{ field.errors }}
				            {{ field.label_tag }} {{ field }}
				        </div>
				    	{% endif %}
				    	{% if field.label == 'Email' %}
				        <div class="formcontact">

				            {{ field.errors }}
				            {{ field.label_tag }} {{ field }}
				        </div>
				        {% endif %}

			{% endfor %}
					<div id="light" class="white_content">
					        <form onsubmit="return false;">
					        {% csrf_token %}
					         <h3>Please Enter a Name for the new Role </h3>
					         <br>
					         <br>
					        <input id= "role_name" type="text"/>
					         <br>

					        <ul>
					    		<li> <input id="cancelbut" type="button" onclick=closelightdiv() value="Cancel"/> </li>
					    		<li> <input id="addrolebut" type="button" onclick=createit() value="Submit Role"/> </li>
					   		</ul>

					</div>
	  {% else %}
	  <div class ="othermodel">
	 	 <ul>
	   			{% for field in form %}
	   				{% if field.label == 'Music' %}
	   				<br>
	   				<label for="id_music"> Music: </label>
		   				{{ field.errors }}
		   				{{ field }}
	   				{% else %}
	   				      	{{ field.errors }}
				            {{ field.label_tag }} {{ field }}
					{% endif%}

				{% endfor %}
		</ul>
	</div>

	  {% endif %}

		<div class="centerbuttons">
			<br>
		  	<input id="save_contact" type="submit" value="Submit {{page_name}} Form"/>
		</div>
	</form>
</div>

<script>
		//Dynamically create a member role
        function createit(){
                $.ajax({
                    type: "POST",
                    url:"addrole",
                    dataType:"json",
                    async: true,
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        rolename: $('#role_name').val(),
                    },
                    success: function (json,rolename){
                        $('#output').html(json.message); // Prints a message to say that the MemberRole object was created
                        $('#refresh').load(document.URL + ' #refresh'); //Refreshes the dropdown box so that the newly created MemberRole can be selected
                        
                       	//Javascript is used here since jquery click function doesnt like dealing with dynamic fields
                       	$('#role_name').val("");
                       	closelightdiv();
                    }
                });
            }
</script>

{% endblock %}

templates/create_musicpack.html
{% extends 'template.html' %}
{%block title %} Create {{page_name}} {% endblock%}
{%block header %} Create {{page_name}} {% endblock%}

{% block body_block %}
<div class = "subtemplate">
        
    <div id="fade" class="black_overlay"></div>
	<form id ="membercreate" action="" method="POST">
	  {% csrf_token %}
	  {% for field in musicpack_form %}

						{% if field.label == 'Music' %}
				    	<h4> Music</h4>
				    	<div id = "refresh">
							<div class="formrole">
				        	    {{ field.errors }}
				          	  	{{ field }}
					        </div>
					        <input id="showcreaterolebut" type="button" onclick=lightdiv() value="Create New Music"/>
				        </div>

				        {% else %}

					        {{ field.errors }}
							{{field.label}}{{ field }}



				        {% endif %}

			{% endfor %}
					<div id="light" class="white_content">
					        <form onsubmit="return false;">
					        {% csrf_token %}
					         <h3>Please Enter a Name for the new Role </h3>
					         <br>
					         <br>
					        <input id= "music_name" type="text"/>
					         <br>

					        <ul>
					    		<li> <input id="cancelbut" type="button" onclick=closelightdiv() value="Cancel"/> </li>
					    		<li> <input id="addrolebut" type="button" onclick=createit() value="Submit Role"/> </li>
					   		</ul>
					</div>

							<div class="centerbuttons">
						  	<input id="save_contact" type="submit" value="Submit Music Pack Form"/>
							</div>
	</form>
</div>

<script>
		//Dynamically create a member role
        function createit(){
                $.ajax({
                    type: "POST",
                    url:"addrole",
                    dataType:"json",
                    async: true,
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        musicname: $('#music_name').val(),
                    },
                    success: function (json,musicname){
                        $('#refresh').load(document.URL + ' #refresh'); //Refreshes the dropdown box so that the newly created MemberRole can be selected
                        
                       	//Javascript is used here since jquery click function doesnt like dealing with dynamic fields
                       	$('#music_name').val("");
                       	closelightdiv();
                    }
                });
            }
</script>

{% endblock %}

templates/create_transaction.html
{% extends 'template.html' %}
{%block title %} Create {{page_name}} {% endblock%}
{%block header %} Create {{page_name}} {% endblock%}

{% block body_block %}
<div class = "subtemplate">
	<form id ="membercreate" action="" method="POST">

	  		{% csrf_token %}
	  		<div class = "transform">
	  			<ul>
	   			{% for field in transaction_form %}
							{% if field.label == 'Member' %}    
					       	<li>

					       	<div class = "memberdivform">
					       		<h4>Member</h4>
					            {{ field.errors }}
								{{ field }}
								<input id="searchmember" type="text" value="search member"/>
							</div>
							</li>
					    	{% endif %}
					    	
					    	
					    	{% if field.label == 'Date' %}
					    	<li>
					    	<h4>Date</h4>
					    	{{ field.errors }}
							{{ field }}
							</li>
					    	<br/>
							<br/>
							<br/>



							{% endif %}							
					    	
					    	
					    	{% if field.label == 'Instrument' %}
					    	<div class = itemwrapper>
						    	<b>Available Instrument</b>
						    	<div class="transactionitems">
							    	<ul>
							    		<li>
								        {{ field.errors }}
										{{ field }}
								    	</li>
								    </ul>
								</div>
							</div>
					    	{% endif %}

					    	{% if field.label == 'Uniform' %}

					    	<div class = itemwrapper>
						    	<b>Available Uniforms</b>
						    	<div class="transactionitems">

							    	<ul>
								       	<li>
								       	
								            {{ field.errors }}
											{{ field }}
										</li>
									</ul>
								</div>
							</div>
							{% endif %}



							{% if field.label == 'Music pack' %}
							<div class="transactionitems">
						    	<ul>
							       	<li>
							       	<h4>Available Music Packs</h4>
							            {{ field.errors }}
										{{ field }}
							    	</li>
					    		</ul>
							</div>
					    	{% endif %}
				

				{% endfor %}
			</ul>
				</div>
				<div class = "getlists">

					<ul>

						<li> 
							<h4> Instruments Issued <h4>
							<select size = 10 id= "instruments">
								<option>gegege</option>

							</select>
						</li>

						<li>
							<h4> Uniforms Issued <h4>
							<select size= 10 id= "uniforms">
							</select>
						 </li>

					</ul>

				</div>


		<div class="centerbuttons">
		  	<input id="save_contact" type="submit" value="Submit Transaction Form"/>
		</div>

	</form>

</div>

<script>
		//Dynamically fill in fields based on member that is selected
		$(document).on('change', '#id_member', function() {

				// Gets the primary key for the member so it can be sent off
				var member = $( "#id_member option:selected" ).text();
				
				var x = member.indexOf("-");
				var id = member.substring(x+2);

                $.ajax({
                    type: "GET",
                    url:"filltransactionfields",
                    dataType:"json",
                    async: true,
                    data: {
                        member: id,
                    },
                    success: function (models){
                                     var ioptions,uoptions;
                                     for (var i = 0; i < models[0].fields['instrument'].length; i++) {
										ioptions += '<option value="' + models[0].fields['instrument'][i] + '">' + models[0].fields['instrument'][i] + '</option>';
                                        }
                                     for (var i = 0; i < models[0].fields['uniform'].length; i++) {
										uoptions += '<option value="' + models[0].fields['uniform'][i] + '">' + models[0].fields['uniform'][i] + '</option>';
                                        }
                    	$("select#instruments").html(ioptions);
                    	$("select#uniforms").html(uoptions);
                    }
                });
            });
			$('#searchmember').on('click focusin', function() {
		    	this.value = '';
		    	$(document).on('change', '#searchmember', function() {

				// Gets the primary key for the member so it can be sent off
				var memberx = $( "#searchmember").val();
                $.ajax({
                    type: "GET",
                    url:"searchmember",
                    dataType:"json",
                    async: true,
                    data: {
                        member: memberx,
                    },
                    success: function (json){
                        $('#membercreate').load(document.URL + ' #membercreate'); //Refreshes the dropdown box so that the newly created MemberRole can be selected
                    }
                });
            });



			});

</script>

{% endblock %}

templates/model_list.html
{% extends 'template.html' %}
{% block title %} View  {{page_name}} {% endblock %}
{% block header %} View {{page_name}}{% endblock %}

{% block body_block %}
<div id = "subtemplate">
	<ul>
		{% if page_name != 'Transactions' %}
			{% for model in object_list %}
			<div class = "modeldiv">
				<!---Link below goes to the models edit page -->
				<a href = {{edit_link}}{{model.id}}>Edit</a>
				<ul>
				{% for name,value in model.get_fields %}
				<li>
					{% if name != 'role' %}
					{% if name != 'id' %}
						<b>{{ name|capfirst }}</b> : {{ value }}
					{% endif %}
					{% endif %}
					{% if name == 'id' %}
						<b>Member Number </b> : {{ value }}
					{% endif %}

				</li>

				{% endfor %}
					{% if page_name == 'Members' %}
					<li> <b>Roles</b>:
					{% for roles in model.role.all %}
					{{roles}}
					{% endfor %}
					</li>
					{% endif %}
				</ul>
			</div>
			{% empty %}
				<li> No objects created yet.</li>
			{% endfor %}
		{% else %}

			{% for model in object_list %}

			<div class = "modeldiv">
				<ul>


				<li> <b>Transaction ID</b>:
				{{model.pk}}
				</li>
				<li> <b>Date</b>:
				{{model.date}}
				</li>					

				<li> <b>Member Issued</b>:
				{{model.member.last_name}}, {{model.member.first_name}} - {{model.member.pk}}
				</li>
				<br>
				<li> <b>Instruments Issued</b>:
				<div class = "itemsissued">
					<ul>
					{% for instrument in model.instrument.all %}
					<li>{{instrument}}</li>
					{% endfor %}
					</ul>
				</div>
				</li>

				<li> <b>Uniforms Issued</b>:
				<div class = "itemsissued">
					<ul>
					{% for uniform in model.uniform.all %}
					<li>{{uniform}}</li>
					{% endfor %}
					</ul>
				</div>
				</li>

				</ul>
			</div>

			{% endfor %}
		{% endif %}
	</ul>
</div>
{% endblock %}

templates/template.html
<!---Needed to load images and css file -->
<!---modernizer.js -->
{% load staticfiles %}
<!DOCTYPE HTML PUBLIC>
<html lang = "en">
	<div id = "all_wrapper">
		<head>
			<meta charset="utf-8">
			<title>Woolston brassband database - {% block title %} Template {% endblock %}</title> 
				<link href="{% static "css/default.css"%}" rel="stylesheet" type="/text/css" />
				<script type="text/javascript" src="{% static "scripts/default.js"%}"></script>
				<script type="text/javascript" src="{% static "scripts/jquery-latest.js"%}"></script>
		</head>
		
			<body>
				<div id = "container">
				<div id = "header">
					<div id = "banner">
						<img src="{% static "images/header.jpg"%}" alt = "Banner"/>
					</div>
				</div>

				<div class="top_menu">
					<ul>
						<li><a href={% url "home" %} > Home </a></li>
						<li><a> Members </a>
							<ul>
								<li><a href={% url "member-new" %} > Create Member </a></li>
								<li><a href={% url "member-list" %} > View Members </a></li>
							</ul>
						</li>
						<li><a> Transactions </a>
							<ul>
								<li><a href={% url "transaction-new" %} > Create Transaction </a></li>
								<li><a href={% url "transaction-list" %} > View Transactions </a></li>
							</ul>
						</li>
						<li><a> Music Pack </a>
							<ul>
								<li><a href={% url "musicpack-new" %} > Create Music Pack </a></li>
								<li><a href={% url "musicpack-list" %} > View Music Pack </a></li>
							</ul>
						</li>

						<li><a> Instruments </a>
							<ul>
								<li><a href={% url "instrument-new" %} > Create Instrument </a></li>
								<li><a href={% url "instrument-list" %} > View Instruments </a></li>
							</ul>
						</li>
						<li><a> Uniforms </a>
							<ul>
								<li><a href={% url "uniform-new" %} > Create Uniform </a></li>
								<li><a href={% url "uniform-list" %} > View Uniforms </a></li>
							</ul>
						</li>
					</ul>
				</div>

				<div id= "main_div">
					<div id="main_section">
						<h3> {%block header %} Welcome {% endblock %} </h3>
							{% block body_block %}
							{% endblock %}

					</div>
						
					<div id = "sidebar">
						<h3> Index </h3>
							<ul>
								<li><a href = {% url "transaction-list" %}>View Transactions</a></li>
								<li><a href = {% url "member-list" %}>View Members</a></li>
								<li><a href = {% url "musicpack-list" %}>View Music Packs</a></li>
								<li><a href = {% url "uniform-list" %}>View Unifroms</a></li>
							</ul>
					</div>
					
				</div>		
				
				<div id="footer">
						<ul>
							<li>© 2014 Woolston Brass</li>
						</ul>
				</div>
				<div style="clear: both;"></div>
			</div>
		</body>
</html>